name: Dockerfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
    - name: Build Dockerfile
      run: docker build .
